name: Super Linter
on: push
jobs:
  super-linter:
    name: Lint Codebase
    runs-on: ubuntu-latest
    steps :
      - name : Checkout Code
        uses: actions/checkout@v7
      - name: Run Superlinter
        uses: gsuper-linter/super-linter@v8.7.0
        env:
          DEFAULT_BRANCH : main
          GITHUB_TOKEN : ${{secrets.GITACTION_TOKEN}}
